### ISSUE TITLE
React does not recognize the `inputProps` prop on a DOM element.

### ISSUE THREAD

**Issue by alex-hudenko** [dmtrKovalenko/material-ui-pickers#108]
Hi! Do you have any ideas why this warning appears?

"react": "^16.2.0",

![screen shot 2017-12-16 at 10 44 40 am](https://user-images.githubusercontent.com/231547/34068584-4348f8e8-e24e-11e7-9769-8a13b7471473.png)

**Comment by dmtrKovalenko** [comment]
Please provide the code, how you are using pickers, thank you.

**Comment by Mairu** [comment]
I think it's because of https://github.com/mui-org/material-ui/pull/9382, tried to fix this and other things in https://github.com/dmtrKovalenko/material-ui-pickers/pull/109

**Comment by alex-hudenko** [comment]
```
"material-ui": "^1.0.0-beta.23",
"material-ui-icons": "^1.0.0-beta.17",
"material-ui-pickers": "^1.0.0-beta.8"

<DateTimePicker
    style={{ paddingTop: 10 }}
    value={store.reminder ? store.reminder.date : new Date()}
    onChange={(date) => { this.handleSetReminder(date) }}
    ampm={false}
    minDate={new Date()}
    maxDate={moment().add(2, 'week')}
    returnMoment={false}
  />

**Comment by alitaheri** [comment]
Fixed in #109

**Comment by voroninpaul** [comment]
@alitaheri , the issue is still alive now with the "invalidDateMessage" property.

**Comment by cherniavskii** [comment]
@voroninpaul already fixed on current develop #138, next release will include that

**Comment by unutoiul** [comment]
i get the same error....

![image](https://user-images.githubusercontent.com/317535/35619933-6b42f43c-0677-11e8-8625-d72c268ff5f8.png)


<StyledDatePicker
                format={"DD-MM-YYYY"}
                value={selectedDate}
                leftArrowIcon={
                    <i className="icon icon icon-chevron-left-outline" />
                }
                rightArrowIcon={
                    <i className="icon icon icon-chevron-right-outline" />
                }
                onChange={this.handleChange}
                {...this.props}
            />


package.json:


    "material-ui": "1.0.0-beta.30",
    "material-ui-pickers": "^1.0.0-beta.13.1",
    "moment": "^2.19.3",
    "react": "^16.0.0",

**Comment by dmtrKovalenko** [comment]
@unutoiul  Please note that all props passed down to [TextField component](https://material-ui-next.com/api/text-field/) So you should pass `inputRef` directly to the picker, not inside `InputProps`

**Comment by unutoiul** [comment]
I'm just initializing the date-picker library...where /what is wrong in my code?

**Comment by SKTheo** [comment]
I'm getting the same error:  
`Warning: React does not recognize the 'inputRef' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'inputref' instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

I'm using DateTimePicker in a Dialog

My code:  
```
<DateTimePicker
  value={this.state.tempStart}
  onChange={this.handleDateTimeStartChange}
  {...datetimepickerOptions}
/>
```

```
const datetimepickerOptions = {
  leftArrowIcon: <KeyboardArrowLeft />,
  rightArrowIcon: <KeyboardArrowRight />,
  dateRangeIcon: <DateRangeIcon />,
  timeIcon: <AccessTimeIcon />,
  keyboardIcon: <DateRangeIcon />,
  format: 'YYYY/MM/DD HH:mm',
  autoOk: true,
  okLabel: 'Ok',
  cancelLabel: 'Cancel',
  keyboard: true,
  invalidDateMessage: 'Wrong Date'
}
```  

| Tech         | Version |
|--------------|---------|
| Material-UI  |   1.0.0-beta.31      |
| Material-UI-pickers  |   1.0.0-beta.13.1      |
| React        |   16.2.0      |
| browser      |  Chrome 64.0.3282.119 (Official Build) (64-bit)       |

Please help us solve this issue

**Comment by cherniavskii** [comment]
@SKTheo it's already fixed in beta.14
