### ISSUE TITLE
TimePicker and DateTimePicker appear not to be working with my React setup/installation settings

### ISSUE THREAD

**Issue by daneasterman** [dmtrKovalenko/material-ui-pickers#24]
Hi there,

First off, thanks very much for creating such a great project. I have had no problems at all with the normal DatePicker, and I've really enjoyed working with this. 

1. **Timepicker** - The "clock-style" time picker UI displays perfectly. But it looks like there might be a typo in the quick usage example as the onChange handler method is `onChange={this.handleDateChange}` when it should be `onChange={this.handleTimeChange}` When I try to console log the time value in my code it shows "undefined". (Full example in my code below). The time value also doesn't change in the text field (like it does for the DatePicker and DateTimePicker).

2. **DateTimePicker** - The formatting / layout / css is not displaying correctly. See screenshot below:

<img width="773" alt="screen shot 2017-10-31 at 11 12 00" src="https://user-images.githubusercontent.com/4712052/32221267-cd21d4fe-be2c-11e7-8e76-1c8838576358.png">

I appreciate that it is more challenging to debug React projects than simpler html/css/vanilla js so I will try to provide as much relevant code / setup info as possible. I'm hoping that it could be something as trivial as the React version or the CSS file used (I followed the docs on this).

**package.json**

```
{
  "name": "material-ui-pickers-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "watch": "webpack-dev-server --content-base dist"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.8.2"
  },
  "dependencies": {
    "material-ui": "^1.0.0-beta.17",
    "material-ui-pickers": "^1.0.0-alpha.8"
  }
}
```

**index.html**

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
      <div id='app'></div>
    <script src="bundle.js"></script>
  </body>
</html>
```

**app.js** (entry point and main container component - v. simple and small React app)

```
import React from 'react';
import ReactDOM from 'react-dom';
import ToggleSwitch from './ToggleSwitch';
import ODDatePicker from './ODDatePicker';

const Main = () => (

  <div style={{marginLeft: '30px'}}>
    
    <ToggleSwitch />    
    <ODDatePicker />

  </div>

  );

const app = document.getElementById('app')
ReactDOM.render(<Main />, app)
```

**ODDatePicker.js**
```
import React from 'react';
// import * as materialIcons from 'material-ui-icons';
import { TimePicker, DatePicker, DateTimePicker } from 'material-ui-pickers';

class ODDatePicker extends React.Component {

  constructor(props) {
    super(props);   
    this.state = { 
      selectedDate: new Date(), 
      selectedTime: new Date()
    };

    this.handleDateChange = this.handleDateChange.bind(this);
    this.handleTimeChange = this.handleTimeChange.bind(this);
    this.handleDateTimeChange = this.handleDateTimeChange.bind(this);
  }

  // N.B: date parameter looks like custom for specific use with this library
  handleDateChange(date) {
    this.setState({ selectedDate: date })
    // console.log( date._d );
     console.log(date);
  }

  handleTimeChange(time) {
    this.setState({ selectedTime: time })
     console.log(time);
  }

  handleDateTimeChange(dateTime) {
    this.setState({ selectedDateTime: dateTime })
    console.log(dateTime);
  }

  render() {
    const { selectedDate, selectedTime, selectedDateTime } = this.state

    return (
      <div>
        
        <DatePicker
          style={{marginTop: '20px'}}
          format={'ddd, MMM DD'}
          value={selectedDate}
          onChange={this.handleDateChange}
        />

        <TimePicker
          style={{marginTop: '30px'}}
          value={selectedTime}
          onChange={this.handleTimeChange}
        />

         <DateTimePicker
          style={{marginTop: '30px'}}
          value={selectedDateTime}
          onChange={this.handleDateTimeChange}
        />         

      </div>
    )
  }

}

export default ODDatePicker;
```

Thanks v. much in advance! (Let me know if you need any more info)

**Comment by dmtrKovalenko** [comment]
Please try to update to v1.0.0-alpha.10.
It should be fixed!

**Comment by daneasterman** [comment]
@dmtrKovalenko thanks very much for this! After updating to alpha 10, the timepicker now works! But unfortunately the datetimepicker still doesn't display correctly (like above). Do you know why this is the case?
Also, not a huge issue, but as a bonus, some of the fonts are displaying as Times rather than Material-UI standard Roboto. Is it possible to fix this or alternatively as a consumer of this project myself, maybe there is something I can do at my end?

**Comment by dmtrKovalenko** [comment]
I will look to the datetimepicker asap.
About fonts - I suggest you to manually add https://github.com/dmtrKovalenko/material-ui-pickers/blob/e6d0102618ee7487ec692bda9f44a41d9a6fa7c7/docs/public/index.html#L13

**Comment by daneasterman** [comment]
thanks @dmtrKovalenko, I added that extra fonts stylesheet now - it changed the font in the text field but not in the modals - this the case for both the date and time pickers.

**Comment by dmtrKovalenko** [comment]
Hmm, thats just really strange) What about materail ui native controls, which font is using for them?

**Comment by daneasterman** [comment]
Ah maybe it's because I'm using the material-ui ^1.0.0-beta.17? (The lead front end developer in our company says we must use this as the stable version is being deprecated). In this beta I'm using the typography component which displays this in the final css for font-family: "Roboto", "Helvetica", "Arial", sans-serif.

**Comment by dmtrKovalenko** [comment]
This library actually using Typography as well, and as well material-ui is just an external for this project, so result should be the same

**Comment by dmtrKovalenko** [comment]
I have completely change displaying views logic for datetime picker so it was fixed in [v1.0.0-alpha.11](https://github.com/dmtrKovalenko/material-ui-pickers/releases/tag/v1.0.0-alpha.11) (I suppose 😄 )

**Comment by daneasterman** [comment]
Awesome! :-) thanks so much @dmtrKovalenko, updated to alpha 11 and it's all working perfectly now! Some fonts still displaying as Times for me (I wonder maybe this is to do with my very simple Webpack installation, maybe the full "create-react" installation will enable full reading of the CSS - just a theory).
Also one more question - do you have type definitions for typescript or have any plans for doing this? (Sorry a developer's job is never done!) Maybe this is something I can help with and contribute in the near future.

**Comment by dmtrKovalenko** [comment]
Hi, I am happy to hear that you trouble have gone.
Yeah typescript definitions its really helpful feature, I have planned to work on it a bit later, but if you won't to help it would be really nice, big thanks to you :)
