### ISSUE TITLE
TypeError: Cannot read property 'date' of undefined

### ISSUE THREAD

**Issue by andrew-w-ross** [dmtrKovalenko/material-ui-pickers#244]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.1     |
| material-ui         |     1.0.0-beta.35    |
| React               |     16.2.0    |
| Browser             |      all   |
| Platform            |     node    |

## Steps to reproduce
1. Clone andrew-w-ross/material-ui-pickers-bug
2. Install and run start

## Expected behavior
The page to render

## Actual behavior
TypeError: Cannot read property 'date' of undefined

**Comment by andrew-w-ross** [comment]
I didn't see the udpated readme.

**Comment by good2hear** [comment]
I'm getting the same error 
how did you solve it?

**Comment by andrew-w-ross** [comment]
@good2hear I didn’t have time to test it out so I stayed on beta. With that being said did you install date-fns@next?

**Comment by good2hear** [comment]
@andrew-w-ross yeap i installed date-fns@next and was still getting the same error.

**Comment by good2hear** [comment]
@andrew-w-ross guess it's fixed with the current one! (1.0.0-rc.2)

**Comment by andrew-w-ross** [comment]
@good2hear  Yeah just checked it out now and it seems to be working

**Comment by pavanshinde47** [comment]
I am still facing the issue. https://codesandbox.io/s/k9y8kz1r1v

**Comment by cherniavskii** [comment]
@pavanshinde47 follow installation guide https://material-ui-pickers.firebaseapp.com/installation

**Comment by pavanshinde47** [comment]
I am doing the same. I have installed the library and my project already using moment. Can you just correct my codesandbox or paste the working code here?

**Comment by TrySound** [comment]
Guys, use `import { MuiPickersUtilsProvider } from 'material-ui-pickers'` please. It should solve the problem.
