### ISSUE TITLE
DateTimePicker time is always 12:00

### ISSUE THREAD

**Issue by oldwin** [dmtrKovalenko/material-ui-pickers#248]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.1        |
| material-ui         | 1.0.0-beta.32        |
| React               |  16.2.0       |
| Browser             | Any        |
| Platform            |  MacOs       |

## Steps to reproduce
1. Render DateTimePicker with MomentUtils and any value

```JavaScript
      <MuiPickersUtilsProvider utils={MomentUtils}>
        <DateTimePicker onChange={(v) => { console.log(v); }} />
      </MuiPickersUtilsProvider>
```
![default](https://user-images.githubusercontent.com/16270391/36986638-eaf5b754-20cc-11e8-9f20-f5a9d24d6a42.png)

## Expected behavior
Time picker shows current value 11:24 pm

## Actual behavior
I always can see 12:00

## Live example
https://codesandbox.io/s/42vj0n08q7

**Comment by dmtrKovalenko** [comment]
Fixed in 1.0.0-rc.2

**Comment by oldwin** [comment]
@dmtrKovalenko still the same issue with rc.2

https://codesandbox.io/s/vyqxmlo010
![default](https://user-images.githubusercontent.com/16270391/37025897-7a04e798-215f-11e8-889c-0e308c0726d9.png)
