### ISSUE TITLE
Change year didn't work 1.0.0-alpha.10

### ISSUE THREAD

**Issue by edidiway** [dmtrKovalenko/material-ui-pickers#25]
Hi again.

Thank you that you have the automatically change the view to date selection after we choose the year, without extra click on "OK" button.

but unfortunately, the year value doesn't change, it only change the header value. 

the scenario is:
1. open calendar dialog
2. click on year Header
3. Choose different year
4. Screen will automatically go back to date selection
5. Choose the date.

**Comment by dmtrKovalenko** [comment]
Fixed in [v1.0.0-alpha.11](https://github.com/dmtrKovalenko/material-ui-pickers/releases/tag/v1.0.0-alpha.11)

**Comment by edidiway** [comment]
hi, are you sure this has been fixed in 1.0.0-alpha.11?
I have installed new version, but the bug still in there.

**Comment by dmtrKovalenko** [comment]
Please refer the demo https://material-ui-pic.firebaseapp.com 
Open it in incognito if you don't see "change all values" button (service worker). There but is not reproducible

**Comment by dmtrKovalenko** [comment]
Seems that nobody report this anymore, it was fixed

**Comment by edidiway** [comment]
hi it is not fixed yet in my application. I have seen your demo link, and it works fine. but not in mine.

my application use this version:
"react": "^15.6.2",
"material-ui": "^1.0.0-beta.20",
"material-ui-pickers": "^1.0.0-alpha.13",

am I the only one who face this issue?

**Comment by dmtrKovalenko** [comment]
Seems yes.
If you are still facing this issue, can you please create webpackbin or smth, that would reproduce that. Thank you.

**Comment by edidiway** [comment]
I think I have found it.
previously I was using react 15.6.2. After upgraded to react 16.1.0, the bug disappear.

**Comment by dmtrKovalenko** [comment]
I am happy to hear that your problem was fixed 😄 
Thank you, I will recheck that for v15.6.2 and fix to maintain the support.
