### ISSUE TITLE
Clicking Today button with autoOk flag enabled should return todays date right away, instead of selecting it in the calendar

### ISSUE THREAD

**Issue by Ethorsen** [dmtrKovalenko/material-ui-pickers#629]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | v1.0.0-rc.14        |
| material-ui         | 1.5.1       |
| React               | 16.4        |
| Browser             | N/A       |
| Peer library        |  moment       | 

## Steps to reproduce
1. Create a Date Picker with showTodayButton and autoOk enabled
2. Open Date Picker
3. Click Today button

## Expected behavior

Date Picker should close and show today date in the field

## Actual behavior

Today date is selected in the calendar

**Comment by dmtrKovalenko** [comment]
Fixed in rc.17

**Comment by rsnay** [comment]
I'm still seeing this issue with

Tech | Version
-- | --
material-ui-pickers | v3.1.0
material-ui | 4.1.1
React | 16.8.6
Browser | N/A
Peer library | date-fns

Did this fix not make it into the newer version, or is there a regression?
