### ISSUE TITLE
After using Provider, the hour and minute positions are reversed in DateTimePicker

### ISSUE THREAD

**Issue by GFwer** [dmtrKovalenko/material-ui-pickers#780]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     2.02   |
| material-ui         |   3.5.1      |
| React               |     16    |
| Browser             |     Chrome 70    |
| Peer library        |    date-io/moment     | 

## Steps to reproduce
1.use date-io/moment and add DateTimePicker

## Actual behavior

position reverse

![image](https://user-images.githubusercontent.com/14303098/48891680-0065f180-ee77-11e8-8d9a-4379aa1b7577.png)
## Live example

https://codesandbox.io/s/q9y0mpylm4

and when I create codesandbox I found if I use my own project,the default icon will not show util I override it,here is the example:https://codesandbox.io/s/2vplvq95x0

**Comment by viict** [comment]
It has been resolved in #775 will be released probably next week as @dmtrKovalenko stated

**Comment by kpala** [comment]
I'm still seeing this behavior with material-ui-pickers 2.0.3 and date-io/date-fns.

Tried with date-fns 2.0.0-alpha.16 and 2.0.0-alpha.21 (the current README refers to both versions, so not sure which one is the current recommendation).

**Comment by dmtrKovalenko** [comment]
Completely fixed in 2.0.4
